profile_register = '🔑 Зарегистрироваться'
hunting_request = '🎯 Подать заявку на охоту'
wh_content = '🎬 Контент Wild-Hunter'
settings = '⚙️ Настройки'
hunter_role_select = 'Стать охотником'
hunting_base_role_select = 'Стать охотхозяйством'
