profile_hunter_register = 'hunter_register'
profile_hunting_base_register = 'hunting_base_register'
hunting_request = 'hunting_request'
wh_content = 'wh_content'
settings = 'settings'
hunter_role_select = 'hunter_role'
hunting_base_role_select = 'hunting_base_role'
main_menu = 'main_menu'
log_out = 'log_out'

hunt_group_request = 'hunt_group_request'
hunt_group_answers = 'hunt_group_answers'
confirm_request = 'confirm_request'
